# -*- coding: utf-8 -*-
"""Exo_code_testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z8PLjjZfNcPz3ukH2WmNnHpR5JDn-200
"""

import pandas as pd

class ShowPlanetInfo():

  def __init__(self):
    pass

  def show_info(self, data, planet):
    # Show info about planet on api/gui
    if planet in data.index:
      exo_planet_index = data.loc[planet]
      return pd.DataFrame(exo_planet_index)
    else:
      return 'Please try again!'